repositories {
    mavenCentral()
    maven { url = "https://maven.seedfinding.com/" }
    maven { url = "https://repo.jellejurre.dev" }
    maven { url = "https://jitpack.io" }
}

dependencies {
    // SeedChecker（关掉传递依赖，避免拉 fabric-loader）
    implementation('com.github.jellejurre:seed-checker:1.2.0-1.17.1-pre1') {
        transitive = false
    }
    // MC core 正式版（它自己带正确版本的 mc_math / mc_seed）
    implementation 'com.seedfinding:mc_core:1.210.0'
    implementation 'com.seedfinding:mc_feature:1.171.9'

    implementation 'org.apache.logging.log4j:log4j-api:2.20.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'
}
