repositories {
    mavenCentral()
    // SeedChecker 官方发布仓（必须）
    maven { url = "https://maven.seedfinding.com/" }
}

dependencies {
    // ✅ 唯一对外依赖，内部传递依赖由它自己管
    implementation 'nl.jellejurre:seedchecker:1.0.2'

    implementation 'org.apache.logging.log4j:log4j-api:2.20.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'

  